### ISSUE TITLE
"Peers list" should be renamed "UNL"

### ISSUE THREAD

**Issue by wilsonianb** [ripple/validator-registry-webapp#2]
`Select a set of validators below for your peers list` -> `Select a set of validators below for your UNL`
`Validators Selected for Peers List` -> `Validators Selected for UNL`

**Comment by stevenzeiler** [comment]
okay will update.

**Comment by stevenzeiler** [comment]
resolved: https://github.com/ripple/validator-registry-webapp/commit/dee8e6a45c5736fa209b26fc67893b24dcad43f8
